{% set name = "vine" %}
{% set version = "1.2.0" %}
{% set sha256 = "ee4813e915d0e1a54e5c1963fde0855337f82655678540a6bc5996bca4165f76" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: {{ build }}
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - pip
    - python
    - setuptools
  run:
    - python

test:
  imports:
    - vine

about:
  home: http://github.com/celery/vine
  license: BSD 3-clause
  license_family: BSD
  license_file: LICENSE
  summary: 'Python promises'

  description: |
    This is a special implementation of promises in that it can be used both
    for promise of a value and lazy evaluation. The biggest upside for this
    is that everything in a promise can also be a promise, e.g. filters,
    callbacks and errbacks can all be promises.
  doc_url: http://vine.readthedocs.io/
  dev_url: https://github.com/celery/vine

extra:
  recipe-maintainers:
    - frol
    - pmlandwehr
